// <auto-generated />
using System;
using DoctorSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904182619_SeedDoctorsAndSpecializations")]
    partial class SeedDoctorsAndSpecializations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "Date", "Time")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DoctorSystem.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Ali",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mohamed Hassan",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Omar Khaled",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Youssef Ahmed",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mahmoud Samir",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Karim Adel",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mostafa Ali",
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Amr Mohamed",
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hassan Ahmed",
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sara Mohamed",
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mariam Ahmed",
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nour Khaled",
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tarek Hassan",
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Khaled Mahmoud",
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ahmed Samy",
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "Islam Ahmed",
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hany Mohamed",
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 18,
                            Name = "Walid Hassan",
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mina Adel",
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 20,
                            Name = "George Samir",
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 21,
                            Name = "Peter Ahmed",
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 22,
                            Name = "Sherif Ali",
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ayman Khaled",
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 24,
                            Name = "Mostafa Hassan",
                            SpecializationId = 8
                        });
                });

            modelBuilder.Entity("DoctorSystem.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dentistry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ENT"
                        });
                });

            modelBuilder.Entity("DoctorSystem.Models.Appointment", b =>
                {
                    b.HasOne("DoctorSystem.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorSystem.Models.Doctor", b =>
                {
                    b.HasOne("DoctorSystem.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("DoctorSystem.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DoctorSystem.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
